server.port=${SERVER_PORT:8085}
spring.application.name=exercises
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ptfitness-exercises}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Pawel123}
